export const dataPicker = [
  {id: 1, value: "água"},
  {id: 2, value: "normal"},
  {id: 3, value: "luta"},
  {id: 4, value: "voo"},
  {id: 5, value: "veneno"},
  {id: 6, value: "terra"},
  {id: 7, value: "rocha"},
  {id: 8, value: "bicho"},
  {id: 9, value: "fantasma"},
  {id: 10, value: "aço"},
  {id: 11, value: "fogo"},
  {id: 12, value: "grama"},
  {id: 13, value: "elétrico"},
  {id: 14, value: "psíquico"},
  {id: 15, value: "gelo"},
  {id: 16, value: "dragão"},
  {id: 17, value: "sombrio"},
  {id: 18, value: "mágico"},
  {id: 19, value: "desconhecido"},
  {id: 20, value: "sombrio"},
]