export const dataPicker = [
  {id: 1, value: "água", label: "água"},
  {id: 2, value: "normal", label: "normal"},
  {id: 3, value: "luta", label: "luta"},
  {id: 4, value: "voo", label: "voo"},
  {id: 5, value: "veneno", label: "veneno"},
  {id: 6, value: "terra", label: "terra"},
  {id: 7, value: "rocha", label: "rocha"},
  {id: 8, value: "bicho", label: "bicho"},
  {id: 9, value: "fantasma", label: "fantasma"},
  {id: 10, value: "aço", label: "aço"},
  {id: 11, value: "fogo", label: "fogo"},
  {id: 12, value: "grama", label: "grama"},
  {id: 13, value: "elétrico", label: "elétrico"},
  {id: 14, value: "psíquico", label: "psíquico"},
  {id: 15, value: "gelo", label: "gelo"},
  {id: 16, value: "dragão", label: "dragão"},
  {id: 17, value: "sombrio", label: "sombrio"},
  {id: 18, value: "mágico", label: "mágico"},
  {id: 19, value: "desconhecido", label: "desconhecido"},
  {id: 20, value: "sombrio", label: "sombrio"},
]